version: '3.3'

services:
  # mongodb:
  #   image: mongo:6.0.1
  #   restart: unless-stopped
  #   command: mongod --port 27018
  #   ports:
  #     - 27018:27018
  #   volumes:
  #     - db:/data/db
  #   networks:
  #     - backend

  backend:
    #depends_on:
    #  - mongodb
    build: ./backend
    restart: always
    ports:
      - 4000:4000
    env_file: ./.env
    environment:
      - MONGODB_DOCKER_PORT=$MONGODB_DOCKER_PORT
      - DB_NAME=$DB_NAME
      - DB_URI=$DB_URI
      - SECRET=$SECRET
      - USERNAME=$USERNAME
      - PASSWORD=$PASSWORD
      - VCENTER=$VCENTER
      - BACKEND_API=$BACKEND_API
      - YANDEX=$YANDEX
      - YAPASS=$YAPASS
    networks:
      - backend
      - frontend

  frontend:
    depends_on:
      - backend
    build:
      context: ./dashboard
    restart: unless-stopped
    ports:
      - 80:80
    env_file: ./.env
    environment:
      - REACT_APP_BACKEND_API=$REACT_APP_BACKEND_API
    networks:
      - backend

volumes:
  db:

networks:
  backend:
  frontend:
